from typing import Any, Callable, Optional, Sequence

import torch

RewardFn = Callable[[torch.Tensor, torch.Tensor], torch.Tensor]
DoneFn = Callable[[torch.Tensor, torch.Tensor, torch.Tensor], torch.Tensor]


class HindsightExperienceReplay:
    """Post-process replay batches with HER goal relabeling.

    Args:
        desired_goal_key: Key for desired goal in sampled batch.
        achieved_goal_key: Key for achieved goal in sampled batch.
        reward_key: Key for reward in sampled batch.
        done_key: Key for done in sampled batch.
        future_suffix: Suffix used by ``future`` strategy (default ``_future``).
        relabel_fraction: Optional relabel probability override in ``[0, 1]``.
            If ``None``, probability is derived from ``replay_strategy`` and
            ``replay_k`` using ``future_p = 1 - 1/(1+k)`` (or ``0`` for
            ``replay_strategy='none'``).
        reward_fn: Optional reward recomputation function
            ``f(achieved_goal, desired_goal) -> reward``.
        env: Optional goal-conditioned env source for reward recomputation.
            If ``reward_fn`` is not provided, HER will try to resolve
            reward function from ``env`` by ``env_reward_fn_name``. For vector
            envs (e.g. ``SyncVectorEnv``), HER will also try ``env.envs[0]``.
        env_reward_fn_name: Reward function name on env. Can be a single name
            or a list/tuple of candidate names. Default: ``"compute_reward"``.
        done_fn: Optional done recomputation function
            ``f(achieved_goal, desired_goal, reward) -> done``.
        achieved_goal_for_reward_key: Optional key override for reward/done
            recomputation (default prefers ``next_{achieved_goal_key}`` if present).
        replay_strategy: Default relabel strategy used in ``process_batch``.
            Supported values: ``future``, ``final``, ``episode``, ``random``, ``none``.
        replay_k: Relabel ratio parameter used to derive ``future_p``.

    Notes:
        The input batch must already contain strategy-aligned relabel goals:
        ``{achieved_goal_key}_future`` / ``_final`` / ``_episode`` / ``_random``.
        These keys can be generated by ``ReplayBuffer.sample_batch(..., her_strategies=...)``.
    """

    _VALID_STRATEGIES = {"future", "final", "episode", "random", "none"}

    def __init__(
        self,
        desired_goal_key: str = "desired_goal",
        achieved_goal_key: str = "achieved_goal",
        reward_key: str = "reward",
        done_key: str = "done",
        future_suffix: str = "_future",
        relabel_fraction: Optional[float] = None,
        reward_fn: Optional[RewardFn] = None,
        done_fn: Optional[DoneFn] = None,
        achieved_goal_for_reward_key: Optional[str] = None,
        replay_strategy: str = "future",
        replay_k: int = 4,
        env: Optional[Any] = None,
        env_reward_fn_name: str | Sequence[str] = "compute_reward",
    ) -> None:
        self._validate_strategy(replay_strategy)
        if replay_k < 0:
            raise ValueError(f"replay_k must be non-negative, got {replay_k}.")
        if relabel_fraction is not None and not 0.0 <= relabel_fraction <= 1.0:
            raise ValueError(
                f"relabel_fraction must be in [0, 1], got {relabel_fraction}."
            )

        self.replay_strategy = replay_strategy
        self.replay_k = replay_k
        self.desired_goal_key = desired_goal_key
        self.achieved_goal_key = achieved_goal_key
        self.reward_key = reward_key
        self.done_key = done_key
        self.future_suffix = future_suffix
        self.future_p = self._resolve_relabel_fraction(
            replay_strategy=self.replay_strategy,
            replay_k=self.replay_k,
            relabel_fraction=relabel_fraction,
        )
        # Backward-compatible alias.
        self.relabel_fraction = self.future_p
        self.reward_fn = reward_fn
        self.env = env
        self.env_reward_fn_names = self._normalize_reward_fn_names(env_reward_fn_name)
        if self.reward_fn is None and self.env is not None:
            self.reward_fn = self._make_env_reward_fn(
                self.env,
                reward_fn_names=self.env_reward_fn_names,
            )
        self.done_fn = done_fn
        self.achieved_goal_for_reward_key = achieved_goal_for_reward_key

    @staticmethod
    def _normalize_reward_fn_names(
        reward_fn_name: str | Sequence[str],
    ) -> tuple[str, ...]:
        if isinstance(reward_fn_name, str):
            names = (reward_fn_name,)
        else:
            names = tuple(reward_fn_name)

        if len(names) == 0:
            raise ValueError("env_reward_fn_name cannot be empty.")
        for name in names:
            if not isinstance(name, str) or not name:
                raise ValueError(
                    "env_reward_fn_name must be a non-empty string or sequence of non-empty strings."
                )
        return names

    @staticmethod
    def _resolve_compute_reward(
        env: Any,
        reward_fn_names: Sequence[str],
    ) -> Optional[Callable[..., Any]]:
        candidates: list[Any] = [env]

        unwrapped = getattr(env, "unwrapped", None)
        if unwrapped is not None and unwrapped is not env:
            candidates.append(unwrapped)

        envs = getattr(env, "envs", None)
        if isinstance(envs, (list, tuple)) and len(envs) > 0:
            first_env = envs[0]
            candidates.append(first_env)
            first_unwrapped = getattr(first_env, "unwrapped", None)
            if first_unwrapped is not None and first_unwrapped is not first_env:
                candidates.append(first_unwrapped)

        for candidate in candidates:
            for fn_name in reward_fn_names:
                fn = getattr(candidate, fn_name, None)
                if callable(fn):
                    return fn
        return None

    @classmethod
    def _make_env_reward_fn(
        cls,
        env: Any,
        reward_fn_names: Sequence[str],
    ) -> RewardFn:
        compute_reward = cls._resolve_compute_reward(env, reward_fn_names=reward_fn_names)
        if compute_reward is None:
            raise ValueError(
                f"Failed to resolve reward function from env by names {list(reward_fn_names)}. "
                "Provide reward_fn explicitly or pass a goal-conditioned env "
                "with a matching reward function (for SyncVectorEnv, sub-envs should expose it)."
            )

        def _env_reward_fn(
            achieved: torch.Tensor,
            desired: torch.Tensor,
        ) -> torch.Tensor:
            achieved_np = achieved.detach().cpu().numpy()
            desired_np = desired.detach().cpu().numpy()
            try:
                reward = compute_reward(achieved_np, desired_np, None)
            except TypeError:
                reward = compute_reward(achieved_np, desired_np)
            return torch.as_tensor(
                reward,
                device=achieved.device,
                dtype=achieved.dtype,
            )

        return _env_reward_fn

    @classmethod
    def _validate_strategy(cls, strategy: str) -> None:
        if strategy not in cls._VALID_STRATEGIES:
            raise ValueError(
                f"Unsupported replay_strategy '{strategy}'. "
                f"Expected one of {sorted(cls._VALID_STRATEGIES)}."
            )

    @staticmethod
    def _resolve_relabel_fraction(
        replay_strategy: str,
        replay_k: int,
        relabel_fraction: Optional[float],
    ) -> float:
        if relabel_fraction is not None:
            return relabel_fraction
        if replay_strategy == "none":
            return 0.0
        return 1.0 - 1.0 / (1.0 + float(replay_k))

    def _get_relabel_goal_key(self, replay_strategy: str) -> Optional[str]:
        if replay_strategy == "none":
            return None
        if replay_strategy == "future":
            return f"{self.achieved_goal_key}{self.future_suffix}"
        return f"{self.achieved_goal_key}_{replay_strategy}"

    def _validate_batch(
        self,
        batch: dict[str, torch.Tensor],
        replay_strategy: str,
    ) -> None:
        if self.desired_goal_key not in batch:
            raise ValueError(f"Key '{self.desired_goal_key}' not found in batch.")
        if self.achieved_goal_key not in batch:
            raise ValueError(f"Key '{self.achieved_goal_key}' not found in batch.")

        relabel_goal_key = self._get_relabel_goal_key(replay_strategy)
        if relabel_goal_key is None:
            return
        if relabel_goal_key not in batch:
            raise ValueError(
                f"Key '{relabel_goal_key}' not found in batch for replay_strategy='{replay_strategy}'. "
                "Provide corresponding relabel goals in replay sampling."
            )

    def _reward_achieved_key(self, batch: dict[str, torch.Tensor]) -> str:
        if self.achieved_goal_for_reward_key is not None:
            return self.achieved_goal_for_reward_key

        candidate = f"next_{self.achieved_goal_key}"
        if candidate in batch:
            return candidate

        return self.achieved_goal_key

    @staticmethod
    def _to_like(value: torch.Tensor, reference: torch.Tensor) -> torch.Tensor:
        value = value.to(dtype=reference.dtype, device=reference.device)
        if value.shape == reference.shape:
            return value

        if value.ndim + 1 == reference.ndim and reference.shape[-1] == 1:
            if value.shape == reference.shape[:-1]:
                return value.unsqueeze(-1)

        if value.ndim == reference.ndim + 1 and value.shape[-1] == 1:
            if value.shape[:-1] == reference.shape:
                return value.squeeze(-1)

        raise ValueError(
            f"Cannot align output shape {tuple(value.shape)} to reference shape {tuple(reference.shape)}."
        )

    @staticmethod
    def _expand_mask(mask: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
        if target.ndim == 1:
            return mask
        return mask.view(mask.shape[0], *([1] * (target.ndim - 1)))

    def process_batch(
        self,
        batch: dict[str, torch.Tensor],
        relabel_fraction: Optional[float] = None,
        replay_strategy: Optional[str] = None,
    ) -> dict[str, torch.Tensor]:
        """Apply HER relabeling to a replay batch.

        Args:
            batch: Sampled replay batch.
            relabel_fraction: Optional override of relabel probability in ``[0, 1]``.
            replay_strategy: Optional per-call strategy override.

        Returns:
            A new batch dict with relabeled ``desired_goal`` and optional
            reward/done recomputation. A boolean ``her_mask`` indicates which
            rows were relabeled.
        """
        strategy = self.replay_strategy if replay_strategy is None else replay_strategy
        self._validate_strategy(strategy)
        self._validate_batch(batch, strategy)

        fraction = self.future_p if relabel_fraction is None else relabel_fraction
        if not 0.0 <= fraction <= 1.0:
            raise ValueError(f"relabel_fraction must be in [0, 1], got {fraction}.")

        desired = batch[self.desired_goal_key]
        batch_size = desired.shape[0]
        device = desired.device

        if strategy == "none" or fraction == 0.0:
            mask = torch.zeros(batch_size, dtype=torch.bool, device=device)
        elif fraction == 1.0:
            mask = torch.ones(batch_size, dtype=torch.bool, device=device)
        else:
            mask = torch.rand(batch_size, device=device) < fraction

        out: dict[str, torch.Tensor] = dict(batch)

        relabeled_goal_key = self._get_relabel_goal_key(strategy)
        relabeled_goal = desired if relabeled_goal_key is None else batch[relabeled_goal_key]

        desired_out = desired.clone()
        desired_out[mask] = relabeled_goal[mask]
        out[self.desired_goal_key] = desired_out

        reward_achieved_key = self._reward_achieved_key(batch)
        if self.reward_fn is not None:
            if reward_achieved_key not in out:
                raise ValueError(f"Key '{reward_achieved_key}' not found in batch.")

            try:
                reward_full = self.reward_fn(
                    out[reward_achieved_key],
                    out[self.desired_goal_key],
                )
            except AttributeError as exc:
                if "compute_reward" in str(exc):
                    raise AttributeError(
                        "reward_fn failed because env reward function is missing. "
                        "Pass reward_fn explicitly or initialize HER with env=... so "
                        "it can resolve the configured reward function from Env/SyncVectorEnv."
                    ) from exc
                raise
            reward_full = torch.as_tensor(reward_full, device=device)

            if self.reward_key in out:
                reward_out = out[self.reward_key].clone()
                reward_full = self._to_like(reward_full, reward_out)
                reward_mask = self._expand_mask(mask, reward_out)
                reward_out = torch.where(reward_mask, reward_full, reward_out)
                out[self.reward_key] = reward_out
            else:
                out[self.reward_key] = reward_full

        if self.done_fn is not None:
            if reward_achieved_key not in out:
                raise ValueError(f"Key '{reward_achieved_key}' not found in batch.")

            if self.reward_key not in out:
                raise ValueError(
                    f"Key '{self.reward_key}' not found in batch. "
                    "Provide reward_fn or include reward in replay batch before using done_fn."
                )

            done_full = self.done_fn(
                out[reward_achieved_key],
                out[self.desired_goal_key],
                out[self.reward_key],
            )
            done_full = torch.as_tensor(done_full, device=device, dtype=torch.bool)

            if self.done_key in out:
                done_out = out[self.done_key].clone().to(dtype=torch.bool)
                done_full = self._to_like(done_full, done_out)
                done_mask = self._expand_mask(mask, done_out)
                done_out = torch.where(done_mask, done_full, done_out)
                out[self.done_key] = done_out
            else:
                out[self.done_key] = done_full

        out["her_mask"] = mask
        return out
